### ISSUE TITLE
Blur effect in Xamarin.Forms project

### ISSUE THREAD

**Issue by dejanbasic** [wcoder/Xamarin.BlurView#6]
Hi, I am trying to implement blur effect in Xamarin.Forms project. I accomplished to get blur effect on iOS, by using built-in platform-specifics, and now I am trying to implement it on Android, by using this library. I tried sample project for Xamarin.Forms, with custom renderer for Android, but everything I get is transparent overlay, which is not blurred at all:

![image](https://user-images.githubusercontent.com/32902057/70712132-63753100-1ce3-11ea-9f6c-8ce308027324.png)

Am I missing something here, or what I am doing wrong?

**Comment by yauhenipakala** [comment]
Hi, sorry for the delay.

This library [currently](https://github.com/wcoder/Xamarin.BlurView/pull/9) does not provide support for Xamarin.Forms out of the box, but you can do it via custom controls or effects.

Also, **highly recommended** to use [Sharpnado.MaterialFrame](https://github.com/roubachof/Sharpnado.MaterialFrame) to make views blurring.
